site_name: CharlesCD
repo_url: https://github.com/octopipe/charlescd
markdown_extensions:
  - markdown_include.include
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon-32x32.png
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - attr_list
  - meta

nav:
  - Home: index.md