# permissions for end users to view circles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: circle-viewer-role
rules:
- apiGroups:
  - charlescd.io
  resources:
  - circles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charlescd.io
  resources:
  - circles/status
  verbs:
  - get
