# permissions for end users to edit circles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: circle-editor-role
rules:
- apiGroups:
  - charlescd.io
  resources:
  - circles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charlescd.io
  resources:
  - circles/status
  verbs:
  - get
