apiVersion: charlescd.io/v1alpha1
kind: Circle
metadata:
  name: circle-new
spec:
  author: Maycon Pacheco
  routing: 
    strategy: default
    default:
      customMatch:
        headers:
          tenantId: "2222"
  environments:
    - key: API_PATH
      value: http://api.default.io
  modules:
    - moduleRef: charlescd-guestbook
      revision: "aaaa"
      overrides:
        - key: '$.spec.template.spec.containers[0].image'
          value: 'mayconjrpacheco/dragonboarding:vegeta'
  
  # TODO(user): Add fields here
