apiVersion: charlescd.io/v1alpha1
kind: Circle
metadata:
  name: circle-default
spec:
  author: Maycon Pacheco
  isDefault: true
  namespace: workspace-2
  routing: 
    strategy: default
    default:
      customMatch:
        headers:
          tenantId: "1111"
  environments:
    - key: API_PATH
      value: http://api.default.io
  modules:
    - name: charlescd-guestbook
      namespace: default
      revision: "aaaa"
      overrides:
        - key: '$.spec.template.spec.containers[0].image'
          value: 'mayconjrpacheco/dragonboarding:goku'
  
  # TODO(user): Add fields here
