name: CI

on:
  push:
    branches:
      - main

jobs: 
  butler:
    name: Run lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: engineerd/setup-kind@v0.5.0
      - name: Build proto
        run: |
          make proto
      - name: Install CRDs
        run: |
          make install
      - name: Run test and coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./... -v
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
    
