name: CI

on:
  push:
    branches:
      - main

jobs: 
  butler:
    name: Butler CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.1
        with:
          minikube version: 'v1.26.1'
          kubernetes version: 'v1.25.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build proto
        run: |
          make proto
      - name: Install CRDs
        run: |
          make install
      - name: Run butler e2e tests
        run: |
          make e2e-test
    
