name: Pre CI

on:
  workflow_call:

jobs:
  cluster:
    name: Run CI pipeline of modules
    runs-on: ubuntu-latest
    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.1
        with:
          minikube version: 'v1.26.1'
          kubernetes version: 'v1.25.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
